
export const rawData = [

    {
        id: 1,
        name: 'Heinz Pepper Sauce',
        qty: 1,
        image: require('../assets/pepperSauce.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '240g-220ml',
    },
    {
        id: 2,
        name: 'Dorritos Cool Ranch',
        qty: 1,
        image: require('../assets/coolRanch.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '240g-220ml',
    },
    {
        id: 3,
        name: 'Khati Gaoa Ghee',
        qty: 1,
        image: require('../assets/ghee.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '240g-220ml',
    },
    {
        id: 4,
        name: 'Twix chocolate bar',
        qty: 1,
        image: require('../assets/chocolate.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '5x(2*25g)',
    },
    {
        id: 5,
        name: 'Orange',
        qty: 1,
        image: require('../assets/eat_fresh_1.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '240g-220ml',
    },
    {
        id: 6,
        name: 'Tomato',
        qty: 1,
        image: require('../assets/eat_fresh_2.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '240g-220ml',
    },
    {
        id: 7,
        name: 'Broccoli',
        qty: 1,
        image: require('../assets/eat_fresh_3.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '403g Aprox.'
    },
    {
        id: 8,
        name: 'Twix chocolate bar',
        qty: 1,
        image: require('../assets/vegetable.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '5x(2*25g)',
    },
    {
        id: 9,
        name: 'Onion (Deshi)',
        qty: 1,
        image: require('../assets/eat_fresh_4.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '1 kg'
    },
    {
        id: 10,
        name: 'Onion (Indian)',
        qty: 1,
        image: require('../assets/eat_fresh_4.png'),
        price: 899,
        discount_price: 699,
        discountPercentage: 'Save 29%',
        specialDiscount: null,
        umo: '1 kg'
    },
    {
        id: 11,
        name: 'Close up tooth paste',
        price: 899,
        discount_price: 699,
        image: require('../assets/vegetable.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 12,
        name: 'teer oil',
        price: 899,
        discount_price: 699,
        image: require('../assets/vegetable.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 13,
        name: 'Aroma oil',
        price: 899,
        discount_price: 699,
        image: require('../assets/vegetable.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 14,
        name: 'Dark cocolate',
        price: 899,
        discount_price: 699,
        image: require('../assets/vegetable.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 15,
        name: 'Mango himsagore',
        price: 899,
        discount_price: 699,
        image: require('../assets/breakfast.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 16,
        name: 'Product Name can be long',
        price: 899,
        discount_price: 699,
        image: require('../assets/breakfast.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 17,
        name: 'Product Name can be long',
        price: 899,
        discount_price: 699,
        image: require('../assets/breakfast.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 18,
        name: 'Product Name can be long',
        price: 899,
        discount_price: 699,
        image: require('../assets/breakfast.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 19,
        name: 'Product Name can be long',
        price: 899,
        discount_price: 699,
        image: require('../assets/breakfast.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 20,
        name: 'Product Name can be long',
        price: 899,
        discount_price: 699,
        image: require('../assets/breakfast.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 21,
        name: 'Product Name can be long',
        price: 899,
        discount_price: 699,
        image: require('../assets/breakfast.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 22,
        name: 'Product Name can be long',
        price: 899,
        discount_price: 699,
        image: require('../assets/breakfast.png'),
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',
    },
    {
        id: 23,
        name: 'Product Name can be long',
        image: require('../assets/rice_2.png'),
        price: 899,
        discount_price: 699,
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',

    },
    {
        id: 24,
        name: 'Pran Minicate Premium Rice',
        image: require('../assets/rice_2.png'),
        price: 899,
        discount_price: 699,
        discountRate: 29,
        qty: 1,

    },
    {
        id: 25,
        name: 'Product Name can be long',
        image: require('../assets/rice_2.png'),
        price: 899,
        discount_price: 699,
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',

    },
    {
        id: 26,
        name: 'Product Name can be long',
        image: require('../assets/rice_2.png'),
        price: 899,
        discount_price: 699,
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',

    },
    {
        id: 27,
        name: 'Product Name can be long',
        image: require('../assets/spices_2.png'),
        price: 899,
        discount_price: 699,
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',

    },
    {
        id: 28,
        name: 'Product Name can be long',
        image: require('../assets/spices_2.png'),
        price: 899,
        discount_price: 699,
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',

    },
    {
        id: 29,
        name: 'Digestive biscuit',
        image: require('../assets/spices_2.png'),
        price: 35,
        discount_price: 30,
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',

    },
    {
        id: 30,
        name: 'Noodles',
        image: require('../assets/spices_2.png'),
        price: 899,
        discount_price: 699,
        discountRate: 29,
        qty: 1,
        umo: '220-250ml',

    },

];









